package org.cbihi.mrinormalizer.domain.error;

public enum DicomProcessingError {
    SERIES_NOT_SELECTED,
    SERIES_NOT_FOUND,
    EMPTY_INPUT,
    INPUT_NOT_FOUND,
    INPUT_NOT_READABLE,
    NOT_DICOM,
    DICOM_PARSE_FAILED,
    MIXED_SERIES,
    MIXED_STUDY,
    INCOMPATIBLE_INSTANCE,
    MISSING_REQUIRED_METADATA,
    INVALID_ORIENTATION,
    INVALID_POSITION,
    DUPLICATE_SLICE,
    DUPLICATE_SOP_INSTANCE,
    IRREGULAR_SPACING,
    UNSUPPORTED_OBJECT_TYPE,
    UNSUPPORTED_TRANSFER_SYNTAX,
    UNSUPPORTED_PIXEL_REPRESENTATION,
    PIXEL_DATA_UNAVAILABLE
}
